name: enterprise
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - astropy=4.2
  - async_generator=1.10
  - attrs=20.3.0
  - autoconf=2.69
  - automake=1.16.2
  - mpi=1.0
  - mpich=3.3.2
  - mpi4py=3.0.3
  - backcall=0.2.0
  - basemap=1.2.0
  - blas=1.0
  - bleach=3.2.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.4
  - cfitsio=3.470
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ephem=3.7.7.1
  - expat=2.2.10
  - fftw=3.3.8
  - fontconfig=2.13.0
  - freetype=2.10.4
  - geos=3.8.0
  - glib=2.66.1
  - gsl=2.6
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - healpy=1.14.0
  - icu=58.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.1
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.0
  - krb5=1.18.2
  - lcms2=2.11
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libxml2=2.9.10
  - llvm-openmp=11.0.0
  - lz4-c=1.9.2
  - m4=1.4.18
  - make=4.2.1
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - metis=5.1.0
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.0.4
  - more-itertools=8.6.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.1.6
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.2.0
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pcre=8.44
  - perl=5.26.2
  - pexpect=4.8.0
  - pgplot=5.2.2
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - pluggy=0.13.1
  - proj4=5.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - ptyprocess=0.7.0
  - py=1.10.0
  - pycparser=2.20
  - pyerfa=1.7.1.1
  - pygments=2.7.3
  - pyparsing=2.4.7
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pyshp=2.1.2
  - pytest=6.2.1
  - pytest-runner=5.2
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.5
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - suitesparse=5.7.2
  - scikit-sparse=0.4.4
  - scipy=1.6.0
  - send2trash=1.5.0
  - setuptools=51.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tbb=2020.3
  - tempo2=2020.07.1
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - git+https://github.com/dfm/acor@master
    - corner==2.1.0
    - emcee==3.0.2
    - git+https://github.com/nanograv/enterprise@master
    - git+https://github.com/nanograv/enterprise_extensions@master
    - future==0.18.2
    - jplephem==2.15
    - git+https://github.com/vallis/libstempo@master
    - git+https://github.com/nanograv/PINT@master
    - git+https://github.com/jellis18/PTMCMCSampler@master
    - setuptools-scm==5.0.1
    - uncertainties==3.1.5
